SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS ON 
GO

-- 创建主表LANDMEN
IF OBJECT_ID(N'MASTER.DBO.LANDMEN', N'U') IS NULL
BEGIN
	CREATE TABLE DBO.LANDMEN (
        ID INT IDENTITY(1,1) PRIMARY KEY,
        ABNAME NVARCHAR(20) UNIQUE NOT NULL,
        DBNAME NVARCHAR(20) UNIQUE NOT NULL,
        CRTDATE DATETIME NOT NULL 
	)
END
GO

-- 创建GETAB
IF OBJECT_ID(N'MASTER.DBO.GETAB', N'P') IS NOT NULL
DROP PROCEDURE DBO.GETAB
GO

CREATE PROCEDURE DBO.GETAB AS
BEGIN
	SET NOCOUNT OFF
	SELECT ID, ABNAME, DBNAME, CRTDATE FROM MASTER.DBO.LANDMEN
END
GO


-- 增加账本存储过程

IF OBJECT_ID(N'DBO.ADDAB', N'P') IS NOT NULL
DROP PROCEDURE DBO.ADDAB
GO

CREATE PROCEDURE DBO.ADDAB (@AB NVARCHAR(20), @DB NVARCHAR(20))
AS
BEGIN
	SET NOCOUNT OFF
	INSERT INTO MASTER.DBO.LANDMEN (ABNAME, DBNAME, CRTDATE) VALUES (@AB, @DB, GETDATE());
END
GO

-- 删除账本存储过程

IF OBJECT_ID(N'DBO.DELAB', N'P') IS NOT NULL
DROP PROCEDURE DBO.DELAB
GO

CREATE PROCEDURE DBO.DELAB (@RET INT OUTPUT, @ID INT)
AS
DECLARE @DB NVARCHAR(20)
DECLARE @CMD NVARCHAR (100)
SET @DB=''
BEGIN
	SET NOCOUNT OFF
	SELECT @DB = (SELECT DBNAME FROM MASTER.DBO.LANDMEN WHERE ID=@ID )
	IF @DB != ''
		BEGIN
			SET @CMD = 'ALTER DATABASE '+ @DB +' SET SINGLE_USER WITH ROLLBACK IMMEDIATE'
			EXEC (@CMD)
			SET @CMD = 'DROP DATABASE ' + @DB
			EXEC (@CMD) 
			DELETE FROM MASTER.DBO.LANDMEN WHERE ID = @ID	
			SET @RET=1
		END
	ELSE
		SET @RET=0
END
GO

